<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>hkx_reflect</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="HKX2">
      <HintPath>..\..\vendor\HKX2.dll</HintPath>
    </Reference>
    <Reference Include="SoulsFormats">
      <HintPath>..\..\vendor\SoulsFormats.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
